spring.application.name=customer-service
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/demo}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:demo}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:demo}
spring.datasource.hikari.initialization-fail-timeout=60000
server.error.include-message=always
spring.sql.init.mode=always
